### ISSUE TITLE
GetInstanceLoaderManager use of undeclared identifier.

### ISSUE THREAD

**Issue by leyafo** [vczh-libraries/iGac#1]
It seems load GUI xml resources, These code documents are so poor. 
Brother lunzi has no documents for this code. How to fix this issue?

**Comment by vczh** [comment]
@leyafo Use GetResourceManager instead. This function declares in GacUI.h, because in the comming feature, you can get rid of GacUIReflection.h if you don't need metadata in runtime. And you still need a place to "SetResource" anyway.

**Comment by vczh** [comment]
@leyafo Refer to my tutorials' Main.cpp files.

**Comment by darkfall** [comment]
Hmmm... seems I need to update this again : )

**Comment by vczh** [comment]
@darkfall 刚发的update，今天凌晨已经qq你了呀（逃

**Comment by darkfall** [comment]
updated
