### ISSUE TITLE
为了让你写demo更方便

### ISSUE THREAD

**Issue by vczh** [vczh-libraries/iGac#3]
@darkfall ：
现在GacUI.h里面不是自带了只对osx不可见的using namespace吗，你说如果让你以后可以少改点demo的代码，哪个比较好？

1、直接删掉，我分别在每一个Demo里面加所有的using namespace
2、写成这样：
namespace gacui_namespaces
{
    using namespace vl;
    using namespace vl::presentation;
    ...
}
然后我每一个demo去using namespace gacui_namespaces;， 这样就等于复制了所有的using namespace？

**Comment by darkfall** [comment]
2吧. 比较好控制. 

真要方便还是merge了以后才方便，就不用copy来copy去了（逃

**Comment by vczh** [comment]
@darkfall  我加了一个宏，默认情况下已经没有任何using namespace了。
