### ISSUE TITLE
编译出来的程序运行起来UI控件都显示不出来。

### ISSUE THREAD

**Issue by zhengying** [vczh-libraries/iGac#4]
全部都是这样的：
![2016-04-24 23 21 16](https://cloud.githubusercontent.com/assets/1042545/14768410/10eaa436-0a74-11e6-9628-9229db60b3f3.png)

我的系统是OSX EI Caption 10.11.4

**Comment by roodkcab** [comment]
confirmed on osx 10.14.6

**Comment by roodkcab** [comment]
label执行了渲染，看起来是层级和背景色的问题，等我调一调

**Comment by roodkcab** [comment]
已经在retina和非retina屏上验证
