### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by iDalink** [vczh-libraries/iGac#6]
make[2]: *** No rule to make target `MacTest/CMakeFiles/GacUI.dir/build'.  Stop.
make[1]: *** [MacTest/CMakeFiles/GacUI.dir/all] Error 2
make: *** [all] Error 2

**Comment by darkfall** [comment]
you have to clone submodules first:

git submodule init
git submodule update

**Comment by vczh** [comment]
@darkfall 说来更新这次release你还缺什么东西吗？
