### ISSUE TITLE
编译报错，找不到成员

### ISSUE THREAD

**Issue by iDalink** [vczh-libraries/iGac#8]
我在CMakeLists.txt里面更改了C++版本，-std=c++14。在MacTest目录下执行make all目标，报这个错误：
In file included from /Users/iflytek/Linux/iGac/Release/Import/GacUI.cpp:5:
/Users/iflytek/Linux/iGac/MacTest/../Release/Import/GacUI.h:15094:33: error: no
      member named 'GetDecoratedDataVisualizer' in
      'vl::presentation::controls::list::IDataVisualizer'
  ...visualizer = visualizer->GetDecoratedDataVisualizer();

**Comment by vczh** [comment]
作者 @darkfall 暂时没空更新，这份代码比较落后。

**Comment by iDalink** [comment]
linux版本可以编译吗？
